services:
  agent:
    image: portainer/agent:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global

  portainer:
    image: portainer/portainer-ce:latest
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    volumes:
      - portainer_data:/data
    networks:
      - agent_network
      - traefik-public # Conecta à rede do Traefik
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        # --- Configuração do Traefik ---
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"

        # --- Roteador para a Interface Web (UI) ---
        - "traefik.http.routers.portainer-ui.rule=Host(`portainer.<YOUR_DOMAIN>`)"
        - "traefik.http.routers.portainer-ui.entrypoints=websecure"
        - "traefik.http.routers.portainer-ui.service=portainer-ui-svc"
        - "traefik.http.routers.portainer-ui.tls.certresolver=letsencrypt"
        
        # --- Serviço da Interface Web (UI) ---
        - "traefik.http.services.portainer-ui-svc.loadbalancer.server.port=9000"
        - "traefik.http.services.portainer-ui-svc.loadbalancer.passHostHeader=true"

networks:
  agent_network:
    driver: overlay
  traefik-public:
    external: true

volumes:
  portainer_data: