global:
  scrape_interval: 15s
  scrape_timeout: 5s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
          - 'localhost:9090'

  - job_name: 'n8n'
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'n8n.dariobastos.me'