services:
  db-krayin:
    image: mariadb:latest
    hostname: '{{.Service.Name}}.{{.Task.Slot}}'
    volumes:
      - mariadb_data_krayin:/var/lib/mysql
    environment:
      - TZ=America/Sao_Paulo
      - MYSQL_DATABASE=krayin
      - MYSQL_ROOT_PASSWORD=${KRAYIN_PASSWORD}
      - MYSQL_USER=${KRAYIN_USER}
    networks:
      - dev-network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  krayin:
    image: webkul/krayin:v2.1.2-https
    hostname: '{{.Service.Name}}.{{.Task.Slot}}'
    volumes:
      - krayin_data:/var/www/html/
    networks:
      - dev-network
      - traefik-public
    environment:
      - krayin_PUBLIC_URL=https://krayin.<YOUR_DOMAIN>
      - APP_URL=https://krayin.<YOUR_DOMAIN>
      - SANCTUM_STATEFUL_DOMAINS=https://krayin.<YOUR_DOMAIN>
      - L5_SWAGGER_UI_PERSIST_AUTHORIZATION=true
      - krayin_CADDY=:80
      - APP_NAME=Krayin
      - APP_LOCALE=pt_BR
      - APP_CURRENCY=BRL
      - APP_TIMEZONE=America/Sao_Paulo
      - LOG_CHANNEL=stderr
      - LOG_LEVEL=debug
      - APP_DEBUG=false
      - BROADCAST_DRIVER=log
      # BANCO DE DADOS
      - DB_CONNECTION=mysql
      - DB_HOST=db-krayin
      - DB_PORT=3306
      - DB_DATABASE=krayin
      - DB_USERNAME=${KRAYIN_USER}
      - DB_PASSWORD=${KRAYIN_PASSWORD}
      - DB_PREFIX=krayin_
    deploy:
      labels:
        # --- Configuração do Traefik ---
        - traefik.enable=true

        # --- Roteador ---
        - traefik.http.routers.krayin.rule=Host(`krayin.<YOUR_DOMAIN>`)
        - traefik.http.routers.krayin.entrypoints=websecure
        - traefik.http.routers.krayin.service=krayin
        - traefik.http.routers.krayin.tls.certresolver=letsencrypt

        # --- Serviço ---
        - traefik.http.services.krayin.loadbalancer.server.port=80
        - traefik.http.services.krayin.loadbalancer.passHostHeader=true
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

volumes:
  mariadb_data_krayin:
  krayin_data:

networks:
  dev-network:
    external: true
  traefik-public:
    external: true