services:
  db-krayin:
    image: mariadb:latest
    hostname: '{{.Service.Name}}.{{.Task.Slot}}'
    volumes:
      - mariadb_data_krayin:/var/lib/mysql
    environment:
      - TZ=America/Sao_Paulo
      - MYSQL_DATABASE=krayin
      - MYSQL_ROOT_PASSWORD=${KRAYIN_PASSWORD}
      - MYSQL_USER=${KRAYIN_USER}
    networks:
      - dev-network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  krayin:
    image: webkul/krayin:v2.1.2-https
    hostname: '{{.Service.Name}}.{{.Task.Slot}}'
    volumes:
      - krayin_data:/var/www/html/
      # - /root/portainer/krayin/branding/favicon.ico:/var/www/html/laravel-crm/public/admin/build/assets/favicon-BtbgZBji.ico:ro Caso queira alterar o favicon descomente
      # - /root/portainer/krayin/branding/logo.svg:/var/www/html/laravel-crm/public/admin/build/assets/logo-Bjh7YAuF.svg:ro Caso queira alterar o logo descomente
      # - /root/portainer/krayin/branding/logo.svg:/var/www/html/laravel-crm/public/admin/build/assets/dark-logo-Dnw3cpYj.svg.svg:ro Caso queira alterar o logo descomente
      # - /root/portainer/krayin/unlock/TrustProxies.php:/var/www/html/laravel-crm/app/Http/Middleware/TrustProxies.php:ro Caso queira desbloquear descomente
    networks:
      - dev-network
      - traefik-public
    environment:
      - krayin_PUBLIC_URL=https://${KRAYIN_URL}
      - APP_URL=https://${KRAYIN_URL}
      - SANCTUM_STATEFUL_DOMAINS=https://${KRAYIN_URL}
      - L5_SWAGGER_UI_PERSIST_AUTHORIZATION=true
      - krayin_CADDY=:80
      - APP_NAME=Krayin
      - APP_LOCALE=pt_BR
      - APP_CURRENCY=BRL
      - APP_TIMEZONE=America/Sao_Paulo
      - LOG_CHANNEL=stderr
      - LOG_LEVEL=debug
      - APP_DEBUG=false
      - BROADCAST_DRIVER=log

      # BANCO DE DADOS
      - DB_CONNECTION=mysql
      - DB_HOST=db-krayin
      - DB_PORT=3306
      - DB_DATABASE=krayin
      - DB_USERNAME=${KRAYIN_USER}
      - DB_PASSWORD=${KRAYIN_PASSWORD}
      - DB_PREFIX=krayin_

      # E-MAIL
      - MAIL_FROM_ADDRESS=${EMAIL_ADDRESS}
      - MAIL_FROM_NAME="${APP_NAME}"
      - MAIL_DRIVER=smtp
      - MAIL_HOST=mailtrap.io
      - MAIL_PORT=993
      - MAIL_USERNAME=${EMAIL_ADDRESS}
      - MAIL_PASSWORD=${EMAIL_PASSWORD}
      - MAIL_ENCRYPTION=ssl
    deploy:
      labels:
        # --- Configuração do Traefik ---
        - traefik.enable=true

        # --- Roteador ---
        - traefik.http.routers.krayin.rule=Host(`${KRAYIN_URL}`)
        - traefik.http.routers.krayin.entrypoints=websecure
        - traefik.http.routers.krayin.service=krayin
        - traefik.http.routers.krayin.tls.certresolver=letsencrypt

        # --- Serviço ---
        - traefik.http.services.krayin.loadbalancer.server.port=80
        - traefik.http.services.krayin.loadbalancer.passHostHeader=true
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

volumes:
  mariadb_data_krayin:
  krayin_data:

networks:
  dev-network:
    external: true
  traefik-public:
    external: true