services:
  mariadb:
    image: mariadb:latest
    hostname: '{{.Service.Name}}.{{.Task.Slot}}'
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      - TZ=America/Sao_Paulo
      - MYSQL_DATABASE=krayin
      - MYSQL_ROOT_PASSWORD=${KRAYIN_PASSWORD}
      - MYSQL_USER=${KRAYIN_USER}
    networks:
      - dev-network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

volumes:
  mariadb_data:

networks:
  dev-network:
    external: true