services:
  mariadb:
    image: mariadb:latest
    hostname: mariadb
    ports: 
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      - TZ=America/Sao_Paulo
      - MYSQL_DATABASE=mariadb
      - MYSQL_ROOT_PASSWORD=${MARIADB_PASSWORD}
      - MYSQL_USER=${MARIADB_USER}
    networks:
      - dev-network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

volumes:
  mariadb_data:

networks:
  dev-network:
    external: true