services:
  postgres:
    hostname: postgres
    image: pgvector/pgvector:pg17
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    command:
      - "postgres"
      - "-c"
      - "max_connections=300"
      - "-c"
      - "shared_buffers=512MB"
      - "-c"
      - "work_mem=8MB"
      - "-c"
      - "maintenance_work_mem=128MB"
      - "-c"
      - "effective_cache_size=1536MB"
      - "-c"
      - "max_files_per_process=1000"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dev-network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

volumes:
  postgres_data:

networks:
  dev-network:
    external: true