services:

  qdrant:
    image: qdrant/qdrant:latest
    hostname: qdrant
    environment:
      # ========== LOGGING ==========
      QDRANT__LOG_LEVEL: "INFO"
      QDRANT__LOGGER__FORMAT: "text"

      # ========== STORAGE - CAMINHOS ==========
      QDRANT__STORAGE__STORAGE_PATH: "/qdrant/storage"
      QDRANT__STORAGE__SNAPSHOTS_PATH: "/qdrant/snapshots"
      QDRANT__STORAGE__TEMP_PATH: "/qdrant/temp"
 
      # ========== STORAGE - SNAPSHOTS ==========
      QDRANT__STORAGE__SNAPSHOTS_CONFIG__SNAPSHOTS_STORAGE: "local"
      # Para usar S3, descomente abaixo e comente a linha acima
      # QDRANT__STORAGE__SNAPSHOTS_CONFIG__SNAPSHOTS_STORAGE: "s3"
      # QDRANT__STORAGE__SNAPSHOTS_CONFIG__S3_CONFIG__BUCKET: "qdrant-snapshots"
      # QDRANT__STORAGE__SNAPSHOTS_CONFIG__S3_CONFIG__REGION: "us-east-1"
      # QDRANT__STORAGE__SNAPSHOTS_CONFIG__S3_CONFIG__ACCESS_KEY: "${S3_ACCESS_KEY}"
      # QDRANT__STORAGE__SNAPSHOTS_CONFIG__S3_CONFIG__SECRET_KEY: "${S3_SECRET_KEY}"

      # ========== STORAGE - PAYLOAD ==========
      QDRANT__STORAGE__ON_DISK_PAYLOAD: "true"

      # ========== STORAGE - WAL ==========
      QDRANT__STORAGE__WAL__WAL_CAPACITY_MB: 32
      QDRANT__STORAGE__WAL__WAL_SEGMENTS_AHEAD: 0

      # ========== PERFORMANCE - THREADS ==========
      QDRANT__STORAGE__PERFORMANCE__MAX_SEARCH_THREADS: 0
      QDRANT__STORAGE__PERFORMANCE__OPTIMIZER_CPU_BUDGET: 0

      # ========== OPTIMIZERS - LIMPEZA ==========
      QDRANT__STORAGE__OPTIMIZERS__DELETED_THRESHOLD: 0.2
      QDRANT__STORAGE__OPTIMIZERS__VACUUM_MIN_VECTOR_NUMBER: 1000

      # ========== OPTIMIZERS - SEGMENTAÇÃO ==========
      QDRANT__STORAGE__OPTIMIZERS__DEFAULT_SEGMENT_NUMBER: 0
      QDRANT__STORAGE__OPTIMIZERS__MAX_SEGMENT_SIZE_KB: null
      QDRANT__STORAGE__OPTIMIZERS__INDEXING_THRESHOLD_KB: 10000

      # ========== OPTIMIZERS - FLUSH ==========
      QDRANT__STORAGE__OPTIMIZERS__FLUSH_INTERVAL_SEC: 5

      # ========== OPTIMIZERS - THREADS ==========
      QDRANT__STORAGE__OPTIMIZERS__MAX_OPTIMIZATION_THREADS: null

      # ========== HNSW INDEX ==========
      QDRANT__STORAGE__HNSW_INDEX__M: 16
      QDRANT__STORAGE__HNSW_INDEX__EF_CONSTRUCT: 100
      QDRANT__STORAGE__HNSW_INDEX__FULL_SCAN_THRESHOLD_KB: 10000
      QDRANT__STORAGE__HNSW_INDEX__MAX_INDEXING_THREADS: 0
      
      # ========== SERVICE - CONFIGURAÇÃO BÁSICA ==========
      QDRANT__SERVICE__MAX_REQUEST_SIZE_MB: 32
      QDRANT__SERVICE__MAX_WORKERS: 0
      QDRANT__SERVICE__HOST: 0.0.0.0
      QDRANT__SERVICE__HTTP_PORT: 6333
      QDRANT__SERVICE__GRPC_PORT: 6334

      # ========== SERVICE - CORS ==========
      QDRANT__SERVICE__ENABLE_CORS: "true" 

      # ========== SERVICE - AUTENTICAÇÃO ==========
      QDRANT__SERVICE__API_KEY: "${QDRANT_API_KEY}"
      QDRANT__SERVICE__READ_ONLY_API_KEY: "${QDRANT_READ_ONLY_API_KEY}"

      # ========== TELEMETRIA ==========
      QDRANT__TELEMETRY_DISABLED: "false"

    volumes:
      - qdrant_store:/qdrant/storage
      - qdrant_snapshots:/qdrant/snapshots
      - qdrant_temp:/qdrant/temp
    networks:
      - traefik-public
      - dev-network
    deploy:
      labels:
        # --- Configuração do Traefik ---
        - traefik.enable=true

        # --- Roteador ---
        - traefik.http.routers.qdrant.rule=Host(`${DOMAIN}`)
        - traefik.http.routers.qdrant.entrypoints=websecure
        - traefik.http.routers.qdrant.service=qdrant
        - traefik.http.routers.qdrant.tls.certresolver=letsencrypt

        # --- Middleware ---
        - traefik.http.routers.qdrant.middlewares=qdrant-compress
        - traefik.http.middlewares.qdrant-compress.compress=true
        
        # --- Serviço ---
        - traefik.http.services.qdrant.loadbalancer.server.port=6333
        - traefik.http.services.qdrant.loadbalancer.passHostHeader=true
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '4.0'
          memory: 8G
        reservations:
          cpus: '2.0'
          memory: 4G

volumes:
  qdrant_store:
  qdrant_snapshots:
  qdrant_temp:

networks:
  dev-network:
    external: true
  traefik-public:
    external: true