services:
  minio:
    image: quay.io/minio/minio:RELEASE.2025-04-22T22-12-26Z
    hostname: minio
    command: server /data --console-address ":9001"
    networks:
      - traefik-public
      - dev-network
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_BROWSER_REDIRECT_URL: https://miniofront.${DOMAIN}
      MINIO_SERVER_URL: https://minioback.${DOMAIN}
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
          limits:
            cpus: '0.5'
            memory: 1024M
      labels:
        - traefik.enable=true
        #SSL 2 endereço publico do Minio
        - traefik.http.routers.minio_s3.rule=Host(`minioback.${DOMAIN}`)
        - traefik.http.routers.minio_s3.tls.certresolver=letsencrypt
        - traefik.http.routers.minio_s3.entrypoints=websecure
        - traefik.http.routers.minio_s3.tls=true
        - traefik.http.routers.minio_s3.service=minio_s3
        - traefik.http.services.minio_s3.loadbalancer.server.port=9000
        #SSL 1 endereço console do minio
        - traefik.http.routers.minio_console.rule=Host(`miniofront.${DOMAIN}`)
        - traefik.http.routers.minio_console.tls.certresolver=letsencrypt
        - traefik.http.routers.minio_console.entrypoints=websecure
        - traefik.http.routers.minio_console.tls=true
        - traefik.http.routers.minio_console.service=minio_console
        - traefik.http.services.minio_console.loadbalancer.server.port=9001

volumes:
  minio_data:
    external: true

networks:
  traefik-public:
    external: true
  dev-network:
    external: true