
services:
  wordpress:
    image: wordpress:6.8.3-apache # Sempre verifique se há uma versão mais recente
    environment:
      TZ: America/Sao_Paulo
      WORDPRESS_DB_HOST: mariadb:3306 # Substitua "mariadb" pelo nome do serviço do banco de dados, se diferente
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: '${WP_USER}'
      WORDPRESS_DB_PASSWORD: '${WP_PASSWORD}'
    volumes:
      - wp-app_data:/var/www/html
    configs:
      - source: wp-php-config
        target: /usr/local/etc/php/conf.d/custom-php.ini
    networks:
      - dev-network
      - traefik-public
    deploy:
      labels:
        # --- Configuração do Traefik ---
        - traefik.enable=true

        # --- Roteador ---
        - traefik.http.routers.wordpress.rule=Host(`${WP_HOST}`)
        - traefik.http.routers.wordpress.entrypoints=websecure
        - traefik.http.routers.wordpress.service=wordpress
        - traefik.http.routers.wordpress.tls.certresolver=letsencrypt
        
        # --- Serviço ---
        - traefik.http.services.wordpress.loadbalancer.server.port=80
        - traefik.http.services.wordpress.loadbalancer.passHostHeader=true
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

configs:
  wp-php-config:
    external: true

volumes:
  wp-app_data:

networks:
  dev-network:
    external: true
  traefik-public:
    external: true