# Configurações básicas
bind 0.0.0.0
port 6379

# Segurança (Substitua pela sua senha)
requirepass SENHA

# Política de Memória para o Langfuse
maxmemory-policy noeviction

# Desativar comandos perigosos
rename-command FLUSHDB ""
rename-command FLUSHALL ""